// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernDesign.MVVM.Models;

namespace ModernDesign.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("MVVMSettings.MVVM.Models.StockDataModel", b =>
                {
                    b.Property<string>("StockName")
                        .HasColumnType("TEXT");

                    b.Property<float>("AvgBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<float>("CurrentBuyPrice")
                        .HasColumnType("REAL");

                    b.Property<float>("ReturnInvestment")
                        .HasColumnType("REAL");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockName");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
